export const ICON_TYPE = {
  USER: 1,
  EDIT_USER: 2,
  DELETE: 3,
  ADD_USER: 4,
  SAVE: 5,
  CANCEL: 6,
  BOX: 7,
  LIST: 8,
  CLOSE: 9,
  SEARCH: 10,
};

export const BUTTON_TYPE = {
  PRIMARY: 100,
  SECONDARY: 200,
};

export const ICON_SIZE = {
  REGULAR: 100,
  LARGE: 200,
  X_LARGE: 300,
};

export const ICON_COLOR = {
  LIGHT: 100,
  SHADE: 200,
};

export const ACTIONS = {
  ADD_CUSTOMER: "ADD_CUSTOMER",
  UPDATE_CUSTOMER: "UPDATE_CUSTOMER",
  DELETE_CUSTOMER: "DELETE_CUSTOMER",
  ADD: "ADD",
  EDIT: "EDIT",
  DELETE: "DELETE",
};
